/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull exe'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 7
 * Build: 1.0.0
 * Runtime: browser:typescript-ampli-v2
 *
 * [View Tracking Plan](https://data.amplitude.com/productminds/Facu-test-dev/events/main/latest)
 *
 * [Full Setup Instructions](https://data.amplitude.com/productminds/Facu-test-dev/implementation/exe)
 */

import * as amplitude from '@amplitude/analytics-browser';

export type Environment = 'facutestdev';

export const ApiKey: Record<Environment, string> = {
  facutestdev: '577a483cbeb81dce53c69d6298da22b7'
};

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration: BrowserOptions = {
  plan: {
    version: '7',
    branch: 'main',
    source: 'exe',
    versionId: '0cff2d9f-96e5-409f-aa8b-c4c924701252'
  },
  ...{
    ingestionMetadata: {
      sourceName: 'browser-typescript-ampli',
      sourceVersion: '2.0.0'
    }
  }
};

export interface LoadOptionsBase { disabled?: boolean }

export type LoadOptionsWithEnvironment = LoadOptionsBase & { environment: Environment; client?: { configuration?: BrowserOptions; }; };
export type LoadOptionsWithApiKey = LoadOptionsBase & { client: { apiKey: string; configuration?: BrowserOptions; } };
export type LoadOptionsWithClientInstance = LoadOptionsBase & { client: { instance: BrowserClient; } };

export type LoadOptions = LoadOptionsWithEnvironment | LoadOptionsWithApiKey | LoadOptionsWithClientInstance;

export interface IdentifyProperties {
  "Ejemplo 1"?: string;
  Ejemplo2?: string;
  email?: string;
  trait3?: string;
}

export interface Evento2Properties {
  /**
   * | Rule | Value |
   * |---|---|
   * | Item Type | string |
   */
  je: string[];
}

export interface Evento1Properties {
  eje: string;
  Propiedad1: string;
}

export interface EventoConArrayProperties {
  /**
   * | Rule | Value |
   * |---|---|
   * | Item Type | string |
   */
  arrayBien?: string[];
  /**
   * | Rule | Value |
   * |---|---|
   * | Regex |  |
   */
  arrayString?: string;
}

export interface PruebaAmpliProperties {
  /**
   * | Rule | Value |
   * |---|---|
   * | Regex |  |
   */
  propiedad_a_mantener?: string;
  /**
   * | Rule | Value |
   * |---|---|
   * | Regex |  |
   */
  propiedad_a_mergear?: string;
}

export class Identify implements BaseEvent {
  event_type = amplitude.Types.SpecialEventType.IDENTIFY;

  constructor(
    public event_properties?: IdentifyProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class Evento2 implements BaseEvent {
  event_type = 'Evento 2';

  constructor(
    public event_properties: Evento2Properties,
  ) {
    this.event_properties = event_properties;
  }
}

export class Evento1 implements BaseEvent {
  event_type = 'Evento1';

  constructor(
    public event_properties: Evento1Properties,
  ) {
    this.event_properties = event_properties;
  }
}

export class EventoConArray implements BaseEvent {
  event_type = 'eventoConArray';

  constructor(
    public event_properties?: EventoConArrayProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class PruebaAmpli implements BaseEvent {
  event_type = 'PruebaAmpli';

  constructor(
    public event_properties?: PruebaAmpliProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export type PromiseResult<T> = { promise: Promise<T | void> };

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
  private disabled: boolean = false;
  private amplitude?: BrowserClient;

  get client(): BrowserClient {
    this.isInitializedAndEnabled();
    return this.amplitude!;
  }

  get isLoaded(): boolean {
    return this.amplitude != null;
  }

  private isInitializedAndEnabled(): boolean {
    if (!this.amplitude) {
      console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
      return false;
    }
    return !this.disabled;
  }

  /**
   * Initialize the Ampli SDK. Call once when your application starts.
   *
   * @param options Configuration options to initialize the Ampli SDK with.
   */
  load(options: LoadOptions): PromiseResult<void> {
    this.disabled = options.disabled ?? false;

    if (this.amplitude) {
      console.warn('WARNING: Ampli is already intialized. Ampli.load() should be called once at application startup.');
      return getVoidPromiseResult();
    }

    let apiKey: string | null = null;
    if (options.client && 'apiKey' in options.client) {
      apiKey = options.client.apiKey;
    } else if ('environment' in options) {
      apiKey = ApiKey[options.environment];
    }

    if (options.client && 'instance' in options.client) {
      this.amplitude = options.client.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      const configuration = (options.client && 'configuration' in options.client) ? options.client.configuration : {};
      return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...configuration });
    } else {
      console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
    }

    return getVoidPromiseResult();
  }

  /**
   * Identify a user and set user properties.
   *
   * @param userId The user's id.
   * @param properties The user properties.
   * @param options Optional event options.
   */
  identify(
    userId: string | undefined,
    properties?: IdentifyProperties,
    options?: EventOptions,
  ): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options,  user_id: userId};
    }

    const amplitudeIdentify = new amplitude.Identify();
    const eventProperties = properties;
    if (eventProperties != null) {
      for (const [key, value] of Object.entries(eventProperties)) {
        amplitudeIdentify.set(key, value);
      }
    }
    return this.amplitude!.identify(
      amplitudeIdentify,
      options,
    );
  }

 /**
  * Flush the event.
  */
  flush() : PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.flush();
  }

  /**
   * Track event
   *
   * @param event The event to track.
   * @param options Optional event options.
   */
  track(event: Event, options?: EventOptions): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.track(event, undefined, options);
  }

  /**
   * Evento 2
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Facu-test-dev/events/main/latest/Evento%202)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. je)
   * @param options Amplitude event options.
   */
  evento2(
    properties: Evento2Properties,
    options?: EventOptions,
  ) {
    return this.track(new Evento2(properties), options);
  }

  /**
   * Evento1
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Facu-test-dev/events/main/latest/Evento1)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. eje)
   * @param options Amplitude event options.
   */
  evento1(
    properties: Evento1Properties,
    options?: EventOptions,
  ) {
    return this.track(new Evento1(properties), options);
  }

  /**
   * eventoConArray
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Facu-test-dev/events/main/latest/eventoConArray)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. arrayBien)
   * @param options Amplitude event options.
   */
  eventoConArray(
    properties?: EventoConArrayProperties,
    options?: EventOptions,
  ) {
    return this.track(new EventoConArray(properties), options);
  }

  /**
   * PruebaAmpli
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Facu-test-dev/events/main/latest/PruebaAmpli)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. propiedad_a_mantener)
   * @param options Amplitude event options.
   */
  pruebaAmpli(
    properties?: PruebaAmpliProperties,
    options?: EventOptions,
  ) {
    return this.track(new PruebaAmpli(properties), options);
  }
}

export const ampli = new Ampli();

// BASE TYPES
type BrowserOptions = amplitude.Types.BrowserOptions;

export type BrowserClient = amplitude.Types.BrowserClient;
export type BaseEvent = amplitude.Types.BaseEvent;
export type IdentifyEvent = amplitude.Types.IdentifyEvent;
export type GroupEvent = amplitude.Types.GroupIdentifyEvent;
export type Event = amplitude.Types.Event;
export type EventOptions = amplitude.Types.EventOptions;
export type Result = amplitude.Types.Result;
